/* eslint-disable */
export default {
  "key": "common",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "flags": "flags",
        "games": "games",
        "pets": "pets",
        "finance": "finance",
        "metrics": "metrics",
        "total_rounds": "Total rounds",
        "current_streak": "Current Streak",
        "best_streak": "Best Streak",
        "overall_accuracy": "Overall Accuracy",
        "last_played": "Last played",
        "correct": "correct",
        "errors": "errors",
        "accuracy": "accuracy",
        "delete_card_title": "Delete this card?",
        "delete_card_description": "This will remove the card from this deck.",
        "days": "days",
        "date": "Date",
        "total": "Total",
        "form_select_placeholder": "—",
        "auth_field_name": "Name",
        "auth_field_name_placeholder": "Enter your name",
        "auth_field_email": "Email",
        "auth_field_email_placeholder": "Enter your email",
        "auth_field_password": "Password",
        "auth_field_password_placeholder": "Enter your password",
        "auth_field_password_create_placeholder": "Create a password",
        "auth_field_confirm_password": "Confirm Password",
        "auth_field_confirm_password_placeholder": "Confirm your password",
        "auth_sign_in": "Sign In",
        "auth_sign_up": "Create Account",
        "auth_validation_email_required": "Email is required.",
        "auth_validation_email_invalid": "Enter a valid email.",
        "auth_validation_password_required": "Password is required.",
        "auth_validation_password_too_short": "Password must be at least 8 characters.",
        "auth_validation_name_required": "Name is required.",
        "auth_validation_name_too_short": "Name must be at least 2 characters.",
        "auth_validation_confirm_password_required": "Confirm your password.",
        "auth_validation_passwords_do_not_match": "The passwords do not match.",
        "save": "Save",
        "cancel": "Cancel",
        "edit": "Edit",
        "delete": "Delete",
        "remove": "Remove",
        "close": "Close",
        "search": "Search",
        "load_more": "Load more",
        "try_again": "Try Again",
        "characters": "characters",
        "sign_out": "Sign out",
        "search_no_results": "No results found",
        "announcement_dismiss": "Dismiss",
        "start_game": "Start Game",
        "scoreboard": "Scoreboard",
        "play_again": "Play Again",
        "value": "Value",
        "unit": "Unit",
        "note": "Note",
        "invalid_date": "Enter a valid date",
        "add_reading": "Add reading",
        "needs_more_readings": "Add another reading to see the trend over time.",
        "name": "Name",
        "email": "Email",
        "phone": "Phone",
        "address": "Address",
        "notes": "Notes",
        "back": "Back",
        "copy": "Copy",
        "login": "Sign in",
        "welcome": "Create account",
        "recovery": "Account recovery",
        "animation": "Animation"
      },
      "pt": {
        "flags": "bandeiras",
        "games": "jogos",
        "pets": "pets",
        "finance": "finanças",
        "metrics": "métricas",
        "total_rounds": "Total de rodadas",
        "current_streak": "Sequência Atual",
        "best_streak": "Melhor Sequência",
        "overall_accuracy": "Precisão Geral",
        "last_played": "Última jogada",
        "correct": "corretas",
        "errors": "erros",
        "accuracy": "precisão",
        "delete_card_title": "Excluir este cartão?",
        "delete_card_description": "Isto remove o cartão deste baralho.",
        "days": "dias",
        "date": "Data",
        "total": "Total",
        "form_select_placeholder": "—",
        "auth_field_name": "Nome",
        "auth_field_name_placeholder": "Digite seu nome",
        "auth_field_email": "E-mail",
        "auth_field_email_placeholder": "Digite seu e-mail",
        "auth_field_password": "Senha",
        "auth_field_password_placeholder": "Digite sua senha",
        "auth_field_password_create_placeholder": "Crie uma senha",
        "auth_field_confirm_password": "Confirmar senha",
        "auth_field_confirm_password_placeholder": "Confirme sua senha",
        "auth_sign_in": "Entrar",
        "auth_sign_up": "Criar conta",
        "auth_validation_email_required": "O e-mail é obrigatório.",
        "auth_validation_email_invalid": "Digite um e-mail válido.",
        "auth_validation_password_required": "A senha é obrigatória.",
        "auth_validation_password_too_short": "A senha deve ter ao menos 8 caracteres.",
        "auth_validation_name_required": "O nome é obrigatório.",
        "auth_validation_name_too_short": "O nome deve ter ao menos 2 caracteres.",
        "auth_validation_confirm_password_required": "Confirme sua senha.",
        "auth_validation_passwords_do_not_match": "As senhas não são iguais.",
        "save": "Salvar",
        "cancel": "Cancelar",
        "edit": "Editar",
        "delete": "Excluir",
        "remove": "Remover",
        "close": "Fechar",
        "search": "Buscar",
        "load_more": "Carregar mais",
        "try_again": "Tente novamente",
        "characters": "caracteres",
        "sign_out": "Sair",
        "search_no_results": "Nenhum resultado encontrado",
        "announcement_dismiss": "Dispensar",
        "start_game": "Iniciar Jogo",
        "scoreboard": "Placar",
        "play_again": "Jogar Novamente",
        "value": "Valor",
        "unit": "Unidade",
        "note": "Observação",
        "invalid_date": "Informe uma data válida",
        "add_reading": "Adicionar registro",
        "needs_more_readings": "Registre outra medição para ver a evolução.",
        "name": "Nome",
        "email": "E-mail",
        "phone": "Telefone",
        "address": "Endereço",
        "notes": "Observações",
        "back": "Voltar",
        "copy": "Copiar",
        "login": "Entrar",
        "welcome": "Criar conta",
        "recovery": "Recuperar conta",
        "animation": "Animação"
      }
    }
  },
  "localIds": [
    "common::local::src/i18n/content/common.content.ts"
  ]
} as const;
